name: Build and Deploy
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
